package com.eactive.eai.dto;

import java.io.Serializable;
import java.util.List;

//-----------------------------------------------------------------------------------------------------------
// Generated by eactive DTO Generator, created  : 2017-10-30 11:02:50
//-----------------------------------------------------------------------------------------------------------
public class Person {

    String name;

    int age;

    boolean male;

    List<Address> address;

    boolean state;

    public String getName() {return this.name;}
    public void setName(String value) {this.name = value;}

    public int getAge() {return this.age;}
    public void setAge(int value) {this.age = value;}

    public boolean getMale() {return this.male;}
    public void setMale(boolean value) {this.male = value;}

    public List<Address> getAddress() {return this.address;}
    public void setAddress(List<Address> value) {this.address = value;}

    public boolean getState() {return this.state;}
    public void setState(boolean value) {this.state = value;}

    public static class Address {

        String addr;

        String zipcode;

        public String getAddr() {return this.addr;}
        public void setAddr(String value) {this.addr = value;}

        public String getZipcode() {return this.zipcode;}
        public void setZipcode(String value) {this.zipcode = value;}

        @Override
        public String toString() {
            return "address[addr=" + addr 
            + ", zipcode=" + zipcode 
            + "]";
        }
    }

    @Override
    public String toString() {
        return "person[name=" + name 
        + ", age=" + age 
        + ", male=" + male 
        + ", address=" + address 
        + ", state=" + state 
        + "]";
    }
}
